travis:
  secure:
    BINSTAR_TOKEN: S5JjdZesh57JWrD8magT4fZjO9v+a/WTlZ+dJip7xMXf6OYHmIDCgn5umBWMq252lGv7ipX+CauL3tcKEKT9BJeYciwL9loSEObJ3+NK7GkVNFTO3WCGA375d3z6Fefb5oL/5/F57nL2ZxwW7ya9zvPEQTLB39cf2lnYmynpIc3IheP6rK1EEAU1GlF3KPj1l3GEwY8XxkIz6/m27xxEskuxqCsVKEsj6JMzbGps6Ba24ZraSqla4ohIbYDg/QFOcD6NuaF2MtWiw8YUyMUCF0ZQlNNP5PkKFdJJiHlPNya3FSzKCPr7NmI4zeCsvgq0DjRrhE3AF65ubWcQ3EYwooi+FMC3QU0MHrSWLofqR6Tz7VzaO1dcSTN7xLO+A3zl/9MsdWZ4BDr+9bRaksNoY0vhqAWlLHhMln8mbQ3bmrVzmTewnPqRrjTttlT7O0Bid8zRUSTwXpaxh4DeYF72DM1IcfBKRo789S5gwoiRa01+7TO9bLTyfvuO5U/92UQeupME4aCcVI4yRUnK9kA9uF+KjvHiPJYnqtet1763m2UI0b1fy7TSt0iOpwGkDLg/lWY1gPQu3E7fbEMAZVQXUoY5lEWwsrakWnCfKqeDC9Q/Ss+3Wl3SmjiS+kQB4gees4IIhRxGZAbiCjXIDCO6XmDfWEoXN+Gv1hAOXD21SfA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
