travis:
  secure:
    BINSTAR_TOKEN: dMk+OsrftKmV8jGJJ5YZ7iMaqhBJCSuuZUtTdS2MIvTK/TUGmMV0VH5XLnCR+g09lch4I1Idkad7A/UKizatLMVLbWHWmAQgooCk9UVBx1yOmguz5Ki2xrTzFmuetrcyH94x/2DX+D+gwhstI1iPHMuCmbf0OXLPK5KY6cqZSADK9y9faItmzu9JNgZmT8E50jYhgGMpg4go3G0sCx8kjqF/wUOmxKV7pgirKoRFLDpRYBsQhqcoxsgLGynUcwyh52lUZOtt5kSOdh01vP8femvfNvpv+kCtGH6opt5VCtXl27hKQSGRI2P+7fhhVBZXqxuXf3MCEUt6ItN5izpaER96Qcm70ho4Pc5gMJ+9Kr+Gdi/PDhL6ipl0WZLW1CIygE5XIHOzsfdnz4mpLIeKztZR47S99gLkKmsN90iFf8RICdb2u+uLGG+JWOc+f/72nC0HV56mr6EDfuAbv4rbmxVS4MlhBYqICAATNnVhyLzbzCdB6tOxIsMY/3+UaOLODej0YiVsKkI4OIeWfLnRTA0vxnV1LT+MqQEyWOq61eNGGgJD6l9ZQ22uKotgvIv+eyhKcvBmlnuZpb/LK+ONfYvYiM3TFIrHPdy905P09hv+Dz1JrJ/6/JPRrSLUSBJhNWpexAzYniRSf9P872/qqY1tcEGFLOjCBfN5icJ/wYg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
