appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: m9EFC5Jzx0arnlHWQPvenaPEBMfaGBbmswlZIF0FxBbpoadte+VowxhIM0TlsdDkzj3hd+SfV521Xqv8L+6Zn4Vol5oUR64xbvabE4KiZwzlqTpweMDO72x4B7lXLDywIsJAcShTfc8Jb4I0CMSonbNeM/8pG0YRvkHvhf4yW4OIMWZPeRHUcZe/Ln48CNR//PIOZXzmxZwl4uG6cnfh1GVTJ64e2RK2l/cs5DaZFXvwqQr6fr0QFtQtWSpRUOVfyLLalj/neZx0sRpEGM+bTLlkx4R+p2PupE6z4IoXIWHsSw71JJbCXXYjCmjE2nMfi2YOe9wKoL7xIdgFhhLrhSdll0DHfrdMMUOWKebsvNvVBxJCAx+j9In44oVoWltyrASTM1jLLBjOB/G+J+Jt+Tr2ds0f3ug8dHWmmvqrQjHs5Ihd+TLNHjfaTloJFKxKrGPQSofsUr/gJpAVO/K/Do0hMuB8RG+2QxL93p3ORdKAfw6NgpVFWavYSinucyh27G0qFxqZFUAULGxWmD4BLM/+CKKqhSugjvV5vSCfafVLF7uyS+PVvuMC5RdHVWm1/rejX+1sprY9NNPCaFajAHHD397PEc0/idSnQhZxPYHuSneR3sTnyBgiMeDIdDfjmAdZ6ZAntVG3GEHfb9GseyEw/dZtcmxPa+B/UNIlrOs=
