travis:
  secure:
    BINSTAR_TOKEN: EIgZRoNg6q4uSJA3S0Yhg+IltPhDgVvXsRYm/uQHZW879nkvhLbEVWhJxRASmLeTvYnuxo14f7687u1Q1TbIKs2GnZrbjnbgFwm/uQU2O1PFaMPBlEUP8Z+87dTTHfA6nWmPM6ZdmQy2hQGIypOY2SS7AyC9IkY64uiOo60WbJmEUFDFw3ou7j+WGGDLARS8OF2CIP/7lHtIsW4b1pMKeVeWkwniZIM71gKCuATpwijgZN8KnYmWhzm+xqNksQIgxW8cVhAgVTHAerwxWgErBmlM61VVksaZkK1DfaVCYhh+HkmcrW/7bkqiwFkoAWbuBAyerss+Zoa7PesfNhly6G4FLtmgaukWyp6yoearEAvscCoKHRm4VK/rVQPH7HKbIgZv3JIDP24EV9plmvEYHE6sIM/yZhau6vNbLf8NzgWTMiV3XGlOVgq60jzbFLitKadHC0v2bOAPZmPik6Ekg78TEd+UHfKNs0iSmpGmljWizqnuEcaHzQuZD3BUYJ+eyJLofCKhPG2OBwisOwc7CdwfuzpWMFpGm22SF9JcZGUabZzZU+ou57jHubaAo5M2leuOO7hKU20IV7cANtME58IXaUikXfD7ulULGvT2P+JrhudL5IMVDfCIFr7K2viPORdO/3xkyJ1Jj7SmUWeywAeQAUbF/T/fTRnk8DPyr8g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
