travis:
  secure:
    BINSTAR_TOKEN: nkbBpv5+t4aOUk+TVLpEei2/wYSjfl9rKFTHmm+KA0so9TGgF4zXdxdJELUPQiLF6JtcsPBvOHK386HEXnrnR++zfo4qCKF8X+3yRvB1C+FTzAunWAuI7riBT5lzre5zyGt4yAe2AMJhplnmESjiYwjtpu2r083JRE4o33qzDu0YcfE/pry6jZhenyfzRyY86tWDb9JgNgL5/pdB55dh+JwqYuUICqcry3e+D/v0Gm9aDwlu3kKAKU5mr6fd/N9uzpxzz8xht6/wjmD95jVA86jajLgw8B1JhCDpyr1ufEhK7/XoBx78slYkjMw6/l+w03fFUe7G7EfB+dA7FIUirUmlkZlHZN1GtH2RGaHHfrxLvsmBnb/xz8bmPzTVIYgvug0IFWjGvlX8LF3PFuhsSxaU+dwLfNWM61QTeMEy7YkLOK6XtYKdiLLCzSP0roAejkFtwLkhIfesZda2nHNSM9eIxsW/Hit8NBR++8WopQd2aOe8v5M0PvsGykundlqyf4gbljgLJsoL6Pj7yksn+0JiEZF51dcYrboAVRXORJ9IUrPAuuSYZn24LIVbP8QBahbsxDH1VjVH6GCLJVNEiCnEiJ+9S6v6YzkvvMLRnLZyWlg317DNg3AfvZcVaFJxjJZcVMg1yAymbgVSZUJZc8pS/aSM1h+kD7qRzJ3/v8A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
